
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: feignModule
          uri: lb://feign-service
          predicates:
            - Path=/feign/**
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
