
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: feignModule
          uri: lb://feign-service
          predicates:
            - Path=/feign/**
        - id: restTemplateModule
          uri: lb://resttemplate-service
          predicates:
            - Path=/dashboard/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
